### PR TITLE
Make it work for bike+

### LINKED ISSUE #3: Stats not showing on bike+
TY for the software.

I have a bike+ with Peloton App 2.6.1577. Grupetto shows up fine as the overlay, but all the stats show hyphens only.

I have a Java programming background _(don't know kotlin much)_ and I'm able to use `adb` as well. Let me know if I can assist in a diagnosis.

### PR DESCRIPTION
**Pull request by abhiin1947**
### What is this?
Make it work for Bike+.

Resolves https://github.com/selalipop/grupetto/issues/3

### How did I do this?
Dumped the APKs and tried a bunch of interfaces until one worked. Wrote a different codepath for BikePlus, a new SensorInterface implementation switched by the model number.

It's been a few (good) years since I wrote any Android native code. If I made some silly mistakes, let me know and I'll fix those up :)

### CODE REVIEW

**Comment by ksiegel** [comment]
@abhiin1947 This is absolutely incredible work - I've dreamed of stumbling on some code like this since I bought my Peloton. I've never written Android code before, but this might just inspire me to try and connect this up to sideloaded Zwift.

**Comment by marshyrob** [comment]
Hi @abhiin1947 - Where can i get the APK for this, im not a developer just a bog standard peloton bike+ user wanting to use this feature.  Can an APK be provided so i can sideload please?

Thanks in advance

**Comment by morriswl** [comment]
agree with @marshyrob the APK in releases is not updated to the latest version.

**Comment by marshyrob** [comment]
> agree with @marshyrob the APK in releases is not updated to the latest version.

Hey @morriswl - it was updated just not here, check https://github.com/abhiin1947/grupetto/releases/tag/v0.2.1 Works on my new gen 2 bike+ really good!

**Pull request merged**
